sudo cp /etc/postgresql/{9.6,11}/main/pg_hba.confos: linux
dist: bionic
before_install:
 - date 
 - sudo sed -i 's/port = 5433/port = 5432/' /etc/postgresql/11/main/postgresql.conf
 - sudo cp /etc/postgresql/{9.6,11}/main/pg_hba.conf
 - sudo service postgresql stop
 - sudo service postgresql start 11
 - date
