dist: bionic
group: dev
language: shell
sudo: required
before_install:
    - rvm install 2.6.3
script:
    #  - echo $TRAVIS_APT_PROXY
    #- cat /etc/apt/apt.conf.d/99-travis-apt-proxy
  - ls -al /etc/apt/apt.conf.d
  - lsb_release -a
  - sudo apt-get update && sudo apt-get -y install docker.io 
    #  - for i in {1..10}; do echo $i && curl --connect-timeout 5 -I https://www.google.com | grep "HTTP/2 200" && echo "connected!"; done
addons:
  apt:
    sources:
    - chef-stable-trusty
    packages:
    - chefdk
