language: objective-c
script:
- df -h /
- uname -a
- xcodebuild -version
- system_profiler SPHardwareDataType
- swift -version
- sw_vers
matrix:
  include:
  - os: osx
    osx_image: xcode10.2
  - os: osx
    osx_image: xcode11
