dist: bionic
group: edge
sudo: required
script:
    #  - echo $TRAVIS_APT_PROXY
    #- cat /etc/apt/apt.conf.d/99-travis-apt-proxy
  - ls -al /etc/apt/apt.conf.d
  - for i in {1..10}; do echo $i && curl --connect-timeout 5 -I https://www.google.com | grep "HTTP/2 200" && echo "connected!"; done
