os: linux
dist: bionic
addons:
 apt:
  packages:
   - postgresql-11
   - postgresql-client-11
 postgresql: 11
before_install:
 - date 
 - sudo cp /etc/postgresql/{9.6,11}/main/pg_hba.conf
 - sudo sed -i 's/port = 5433/port = 5432/' /etc/postgresql/11/main/postgresql.conf
 - sudo service postgresql stop
 - sudo service postgresql start 11
 - date
